"""Sensor data ingestion for SteelSense AI.

Loads the synthetic sensor readings and metadata generated by
generate_synthetic_data.py and exposes small, structured summaries for the
agent's tools to hand to the LLM -- never a raw per-timestamp dump.
"""

from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path

import numpy as np
import pandas as pd

DATA_DIR = Path(__file__).resolve().parents[3] / "data" / "sample"


@lru_cache(maxsize=1)
def load_readings() -> pd.DataFrame:
    return pd.read_csv(DATA_DIR / "sensor_readings.csv", parse_dates=["timestamp"])


@lru_cache(maxsize=1)
def load_sensors_meta() -> dict:
    return json.loads((DATA_DIR / "sensors.json").read_text(encoding="utf-8"))


def list_sensors() -> list[dict]:
    return load_sensors_meta()["sensors"]


def resolve_sensor_id(location_or_id: str) -> str | None:
    """Resolve a user-supplied sensor id or location name (case-insensitive)
    to a canonical sensor_id, e.g. "Beam 3A" -> "beam-3a"."""
    query = location_or_id.strip().lower()
    for sensor in list_sensors():
        if query in (sensor["sensor_id"].lower(), sensor["location"].lower()):
            return sensor["sensor_id"]
    return None


def get_sensor_readings(sensor_id: str) -> pd.DataFrame:
    df = load_readings()
    sensor_df = df[df["sensor_id"] == sensor_id].sort_values("timestamp").reset_index(drop=True)
    if sensor_df.empty:
        raise ValueError(f"Unknown sensor_id: {sensor_id!r}")
    return sensor_df


def summarize_sensor(sensor_id: str, days: int | None = None) -> dict:
    """Structured summary stats for a sensor over the last `days` days (or
    the full series if None): mean/std/min/max/latest and a simple linear
    trend. This is what the agent sees -- not raw readings."""
    sensor_df = get_sensor_readings(sensor_id)

    if days is not None:
        cutoff = sensor_df["timestamp"].max() - pd.Timedelta(days=days)
        sensor_df = sensor_df[sensor_df["timestamp"] >= cutoff]

    readings = sensor_df["reading_mv"]
    t_days = (sensor_df["timestamp"] - sensor_df["timestamp"].min()).dt.total_seconds() / 86400
    slope_mv_per_day = 0.0
    if len(sensor_df) > 1 and t_days.max() > 0:
        slope_mv_per_day = float(np.polyfit(t_days, readings, 1)[0])

    meta = next(s for s in list_sensors() if s["sensor_id"] == sensor_id)

    return {
        "sensor_id": sensor_id,
        "location": meta["location"],
        "description": meta["description"],
        "window": {
            "start": sensor_df["timestamp"].min().isoformat(),
            "end": sensor_df["timestamp"].max().isoformat(),
            "n_readings": int(len(sensor_df)),
        },
        "reading_mv": {
            "mean": round(float(readings.mean()), 3),
            "std": round(float(readings.std()), 3),
            "min": round(float(readings.min()), 3),
            "max": round(float(readings.max()), 3),
            "latest": round(float(readings.iloc[-1]), 3),
        },
        "raw_trend_mv_per_day": round(slope_mv_per_day, 4),
        "note": (
            "raw_trend_mv_per_day is uncorrected and includes ambient-"
            "temperature effects. Use the anomaly-detection tool for a "
            "thermally-corrected assessment."
        ),
    }
